version: '3.8'

services:
  api:
    depends_on:
      - auth
      - search
    build:
      context: .
      args:
        APP: "api/main.go"
        PORT: 4444
      dockerfile: Dockerfile.application
    ports:
      - "4444:4444"
    env_file:
      - .env
    volumes:
      - .env:/out/.env
      - type: bind
        source: ${MEDIA_PATH}
        target: ${MEDIA_PATH}

  search:
    depends_on:
      - db
    build:
      context: .
      args:
        APP: "search/search.go"
        PORT: 4442
      dockerfile: Dockerfile.application
    ports:
      - "4442:4442"
    volumes:
      - .env:/out/.env

  auth:
    depends_on:
      - db
    build:
      context: .
      args:
        APP: "auth/auth.go"
        PORT: 4443
      dockerfile: Dockerfile.application
    ports:
      - "4443:4443"
    volumes:
      - .env:/out/.env

  user:
    depends_on:
      - db
    build:
      context: .
      args:
        APP: "user/user.go"
        PORT: 4441
      dockerfile: Dockerfile.application
    ports:
      - "4441:4441"
    volumes:
      - .env:/out/.env
      - type: bind
        source: ${MEDIA_PATH}
        target: ${MEDIA_PATH}

  db:
    build: 
      context: .
      dockerfile: Dockerfile.postgres
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGDATA: "/var/lib/postgresql/data/pgdata"
    ports:
      - 5436:5432
    volumes:
      - ./cmd/internal/db/postgresql/schema/:/docker-entrypoint-initdb.d # isn't used if pgdata exists
      - ${DB_PATH}:/var/lib/postgresql/data
    command: ["postgres"] # "-c", "logging_collector=on", "-c", "log_statement=all"]
