FROM golang:1.20-alpine AS build_stage
ARG APP

WORKDIR /app
COPY . .
RUN go build -o ./out/app_bin cmd/${APP}

# 2 шаг
FROM alpine AS run_stage
ARG PORT

WORKDIR /out
COPY --from=build_stage /app/out/app_bin /out/
RUN chmod +x ./app_bin
EXPOSE ${PORT}/tcp
ENTRYPOINT ./app_bin
