version: '3.8'

services:

  db:
    image: postgres:latest
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - 5436:5432
    volumes:
      - ./cmd/app/internal/db/postgresql/schema/:/docker-entrypoint-initdb.d
