FROM golang:1.20-alpine AS build_stage
WORKDIR /api
COPY . .
RUN go build -o ./out/api_bin cmd/api/main.go

# 2 шаг
FROM alpine AS run_stage
WORKDIR /out
COPY --from=build_stage /api/out/api_bin /out/
RUN chmod +x ./api_bin
EXPOSE 4444/tcp
ENTRYPOINT ./api_bin