version: '3.8'

services:
  api:
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile.Multistage
    env_file:
      - .env
    ports:
      - "4444:4444"
    volumes:
      - ${PWD}/.env:/out/.env

  db:
    image: postgres:latest
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - 5436:5432
    volumes:
      - ./cmd/internal/db/postgresql/schema/:/docker-entrypoint-initdb.d

