global:
  scrape_interval: 15s
  scrape_timeout: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'

    scrape_interval: 10s
    scrape_timeout: 10s

    static_configs:
      - targets:
        - localhost:9090

  - job_name: 'api_server'

    scrape_interval: 5s
    scrape_timeout: 5s

    static_configs:
      - targets:
          #container_name before port (host.docker.internal or localhost don't work)
        - api:4444
        - node_exporter:9100

  
  - job_name: 'auth_server'

    scrape_interval: 5s
    scrape_timeout: 5s

    static_configs:
      - targets:
          #container_name before port (host.docker.internal or localhost don't work)
        - auth:9043
