global:
  scrape_interval: 15s
  scrape_timeout: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'

    scrape_interval: 5s
    scrape_timeout: 5s

    static_configs:
      - targets:
        - localhost:9090

  - job_name: 'api_server'

    scrape_interval: 5s
    scrape_timeout: 5s

    static_configs:
      - targets:
          #container_name before port (host.docker.internal and localhost don't work)
        - 2023_1_technokaif_api_1:4444
