// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package models

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonAe118d8fDecodeGithubComGoParkMailRu20231TechnokaifInternalModels(in *jlexer.Lexer, out *TrackTransfers) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		in.Skip()
		*out = nil
	} else {
		in.Delim('[')
		if *out == nil {
			if !in.IsDelim(']') {
				*out = make(TrackTransfers, 0, 0)
			} else {
				*out = TrackTransfers{}
			}
		} else {
			*out = (*out)[:0]
		}
		for !in.IsDelim(']') {
			var v1 TrackTransfer
			(v1).UnmarshalEasyJSON(in)
			*out = append(*out, v1)
			in.WantComma()
		}
		in.Delim(']')
	}
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonAe118d8fEncodeGithubComGoParkMailRu20231TechnokaifInternalModels(out *jwriter.Writer, in TrackTransfers) {
	if in == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
		out.RawString("null")
	} else {
		out.RawByte('[')
		for v2, v3 := range in {
			if v2 > 0 {
				out.RawByte(',')
			}
			(v3).MarshalEasyJSON(out)
		}
		out.RawByte(']')
	}
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v TrackTransfers) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonAe118d8fEncodeGithubComGoParkMailRu20231TechnokaifInternalModels(w, v)
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *TrackTransfers) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonAe118d8fDecodeGithubComGoParkMailRu20231TechnokaifInternalModels(l, v)
}
func easyjsonAe118d8fDecodeGithubComGoParkMailRu20231TechnokaifInternalModels1(in *jlexer.Lexer, out *TrackTransfer) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "id":
			out.ID = uint32(in.Uint32())
		case "name":
			out.Name = string(in.String())
		case "albumID":
			if in.IsNull() {
				in.Skip()
				out.AlbumID = nil
			} else {
				if out.AlbumID == nil {
					out.AlbumID = new(uint32)
				}
				*out.AlbumID = uint32(in.Uint32())
			}
		case "albumPosition":
			if in.IsNull() {
				in.Skip()
				out.AlbumPosition = nil
			} else {
				if out.AlbumPosition == nil {
					out.AlbumPosition = new(uint32)
				}
				*out.AlbumPosition = uint32(in.Uint32())
			}
		case "artists":
			(out.Artists).UnmarshalEasyJSON(in)
		case "cover":
			out.CoverSrc = string(in.String())
		case "duration":
			out.Duration = uint32(in.Uint32())
		case "listens":
			out.Listens = uint32(in.Uint32())
		case "isLiked":
			out.IsLiked = bool(in.Bool())
		case "recordSrc":
			out.RecordSrc = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonAe118d8fEncodeGithubComGoParkMailRu20231TechnokaifInternalModels1(out *jwriter.Writer, in TrackTransfer) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.Uint32(uint32(in.ID))
	}
	{
		const prefix string = ",\"name\":"
		out.RawString(prefix)
		out.String(string(in.Name))
	}
	if in.AlbumID != nil {
		const prefix string = ",\"albumID\":"
		out.RawString(prefix)
		out.Uint32(uint32(*in.AlbumID))
	}
	if in.AlbumPosition != nil {
		const prefix string = ",\"albumPosition\":"
		out.RawString(prefix)
		out.Uint32(uint32(*in.AlbumPosition))
	}
	{
		const prefix string = ",\"artists\":"
		out.RawString(prefix)
		(in.Artists).MarshalEasyJSON(out)
	}
	{
		const prefix string = ",\"cover\":"
		out.RawString(prefix)
		out.String(string(in.CoverSrc))
	}
	{
		const prefix string = ",\"duration\":"
		out.RawString(prefix)
		out.Uint32(uint32(in.Duration))
	}
	{
		const prefix string = ",\"listens\":"
		out.RawString(prefix)
		out.Uint32(uint32(in.Listens))
	}
	{
		const prefix string = ",\"isLiked\":"
		out.RawString(prefix)
		out.Bool(bool(in.IsLiked))
	}
	{
		const prefix string = ",\"recordSrc\":"
		out.RawString(prefix)
		out.String(string(in.RecordSrc))
	}
	out.RawByte('}')
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v TrackTransfer) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonAe118d8fEncodeGithubComGoParkMailRu20231TechnokaifInternalModels1(w, v)
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *TrackTransfer) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonAe118d8fDecodeGithubComGoParkMailRu20231TechnokaifInternalModels1(l, v)
}
