// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// AuthorizationClient is the client API for Authorization service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AuthorizationClient interface {
	SignUpUser(ctx context.Context, in *SignUpMsg, opts ...grpc.CallOption) (*SignUpResponse, error)
	GetUserByCreds(ctx context.Context, in *Creds, opts ...grpc.CallOption) (*UserResponse, error)
	GetUserByAuthData(ctx context.Context, in *AuthData, opts ...grpc.CallOption) (*UserResponse, error)
	IncreaseUserVersion(ctx context.Context, in *IncreaseUserVersionMsg, opts ...grpc.CallOption) (*Void, error)
	ChangePassword(ctx context.Context, in *ChangePassMsg, opts ...grpc.CallOption) (*Void, error)
}

type authorizationClient struct {
	cc grpc.ClientConnInterface
}

func NewAuthorizationClient(cc grpc.ClientConnInterface) AuthorizationClient {
	return &authorizationClient{cc}
}

func (c *authorizationClient) SignUpUser(ctx context.Context, in *SignUpMsg, opts ...grpc.CallOption) (*SignUpResponse, error) {
	out := new(SignUpResponse)
	err := c.cc.Invoke(ctx, "/auth.Authorization/SignUpUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authorizationClient) GetUserByCreds(ctx context.Context, in *Creds, opts ...grpc.CallOption) (*UserResponse, error) {
	out := new(UserResponse)
	err := c.cc.Invoke(ctx, "/auth.Authorization/GetUserByCreds", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authorizationClient) GetUserByAuthData(ctx context.Context, in *AuthData, opts ...grpc.CallOption) (*UserResponse, error) {
	out := new(UserResponse)
	err := c.cc.Invoke(ctx, "/auth.Authorization/GetUserByAuthData", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authorizationClient) IncreaseUserVersion(ctx context.Context, in *IncreaseUserVersionMsg, opts ...grpc.CallOption) (*Void, error) {
	out := new(Void)
	err := c.cc.Invoke(ctx, "/auth.Authorization/IncreaseUserVersion", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authorizationClient) ChangePassword(ctx context.Context, in *ChangePassMsg, opts ...grpc.CallOption) (*Void, error) {
	out := new(Void)
	err := c.cc.Invoke(ctx, "/auth.Authorization/ChangePassword", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthorizationServer is the server API for Authorization service.
// All implementations must embed UnimplementedAuthorizationServer
// for forward compatibility
type AuthorizationServer interface {
	SignUpUser(context.Context, *SignUpMsg) (*SignUpResponse, error)
	GetUserByCreds(context.Context, *Creds) (*UserResponse, error)
	GetUserByAuthData(context.Context, *AuthData) (*UserResponse, error)
	IncreaseUserVersion(context.Context, *IncreaseUserVersionMsg) (*Void, error)
	ChangePassword(context.Context, *ChangePassMsg) (*Void, error)
	mustEmbedUnimplementedAuthorizationServer()
}

// UnimplementedAuthorizationServer must be embedded to have forward compatible implementations.
type UnimplementedAuthorizationServer struct {
}

func (UnimplementedAuthorizationServer) SignUpUser(context.Context, *SignUpMsg) (*SignUpResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SignUpUser not implemented")
}
func (UnimplementedAuthorizationServer) GetUserByCreds(context.Context, *Creds) (*UserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserByCreds not implemented")
}
func (UnimplementedAuthorizationServer) GetUserByAuthData(context.Context, *AuthData) (*UserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserByAuthData not implemented")
}
func (UnimplementedAuthorizationServer) IncreaseUserVersion(context.Context, *IncreaseUserVersionMsg) (*Void, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IncreaseUserVersion not implemented")
}
func (UnimplementedAuthorizationServer) ChangePassword(context.Context, *ChangePassMsg) (*Void, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ChangePassword not implemented")
}
func (UnimplementedAuthorizationServer) mustEmbedUnimplementedAuthorizationServer() {}

// UnsafeAuthorizationServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AuthorizationServer will
// result in compilation errors.
type UnsafeAuthorizationServer interface {
	mustEmbedUnimplementedAuthorizationServer()
}

func RegisterAuthorizationServer(s grpc.ServiceRegistrar, srv AuthorizationServer) {
	s.RegisterService(&Authorization_ServiceDesc, srv)
}

func _Authorization_SignUpUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignUpMsg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthorizationServer).SignUpUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/auth.Authorization/SignUpUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthorizationServer).SignUpUser(ctx, req.(*SignUpMsg))
	}
	return interceptor(ctx, in, info, handler)
}

func _Authorization_GetUserByCreds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Creds)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthorizationServer).GetUserByCreds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/auth.Authorization/GetUserByCreds",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthorizationServer).GetUserByCreds(ctx, req.(*Creds))
	}
	return interceptor(ctx, in, info, handler)
}

func _Authorization_GetUserByAuthData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthData)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthorizationServer).GetUserByAuthData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/auth.Authorization/GetUserByAuthData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthorizationServer).GetUserByAuthData(ctx, req.(*AuthData))
	}
	return interceptor(ctx, in, info, handler)
}

func _Authorization_IncreaseUserVersion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IncreaseUserVersionMsg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthorizationServer).IncreaseUserVersion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/auth.Authorization/IncreaseUserVersion",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthorizationServer).IncreaseUserVersion(ctx, req.(*IncreaseUserVersionMsg))
	}
	return interceptor(ctx, in, info, handler)
}

func _Authorization_ChangePassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChangePassMsg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthorizationServer).ChangePassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/auth.Authorization/ChangePassword",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthorizationServer).ChangePassword(ctx, req.(*ChangePassMsg))
	}
	return interceptor(ctx, in, info, handler)
}

// Authorization_ServiceDesc is the grpc.ServiceDesc for Authorization service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Authorization_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "auth.Authorization",
	HandlerType: (*AuthorizationServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SignUpUser",
			Handler:    _Authorization_SignUpUser_Handler,
		},
		{
			MethodName: "GetUserByCreds",
			Handler:    _Authorization_GetUserByCreds_Handler,
		},
		{
			MethodName: "GetUserByAuthData",
			Handler:    _Authorization_GetUserByAuthData_Handler,
		},
		{
			MethodName: "IncreaseUserVersion",
			Handler:    _Authorization_IncreaseUserVersion_Handler,
		},
		{
			MethodName: "ChangePassword",
			Handler:    _Authorization_ChangePassword_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "auth.proto",
}
