// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package delivery

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson78ce7faeDecodeGithubComGoParkMailRu20231TechnokaifInternalPkgCsrfDeliveryHttp(in *jlexer.Lexer, out *getCSRFResponce) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "csrf":
			out.CSRF = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson78ce7faeEncodeGithubComGoParkMailRu20231TechnokaifInternalPkgCsrfDeliveryHttp(out *jwriter.Writer, in getCSRFResponce) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"csrf\":"
		out.RawString(prefix[1:])
		out.String(string(in.CSRF))
	}
	out.RawByte('}')
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v getCSRFResponce) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson78ce7faeEncodeGithubComGoParkMailRu20231TechnokaifInternalPkgCsrfDeliveryHttp(w, v)
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *getCSRFResponce) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson78ce7faeDecodeGithubComGoParkMailRu20231TechnokaifInternalPkgCsrfDeliveryHttp(l, v)
}
