// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package http

import (
	json "encoding/json"
	http "github.com/go-park-mail-ru/2023_1_Technokaif/internal/pkg/user/delivery/http"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonE5772aeDecodeGithubComGoParkMailRu20231TechnokaifInternalPkgPlaylistDeliveryHttp(in *jlexer.Lexer, out *playlistUpdateInput) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "name":
			out.Name = string(in.String())
		case "users":
			if in.IsNull() {
				in.Skip()
				out.UsersID = nil
			} else {
				in.Delim('[')
				if out.UsersID == nil {
					if !in.IsDelim(']') {
						out.UsersID = make([]uint32, 0, 16)
					} else {
						out.UsersID = []uint32{}
					}
				} else {
					out.UsersID = (out.UsersID)[:0]
				}
				for !in.IsDelim(']') {
					var v1 uint32
					v1 = uint32(in.Uint32())
					out.UsersID = append(out.UsersID, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "description":
			if in.IsNull() {
				in.Skip()
				out.Description = nil
			} else {
				if out.Description == nil {
					out.Description = new(string)
				}
				*out.Description = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonE5772aeEncodeGithubComGoParkMailRu20231TechnokaifInternalPkgPlaylistDeliveryHttp(out *jwriter.Writer, in playlistUpdateInput) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"name\":"
		out.RawString(prefix[1:])
		out.String(string(in.Name))
	}
	{
		const prefix string = ",\"users\":"
		out.RawString(prefix)
		if in.UsersID == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v2, v3 := range in.UsersID {
				if v2 > 0 {
					out.RawByte(',')
				}
				out.Uint32(uint32(v3))
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"description\":"
		out.RawString(prefix)
		if in.Description == nil {
			out.RawString("null")
		} else {
			out.String(string(*in.Description))
		}
	}
	out.RawByte('}')
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v playlistUpdateInput) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonE5772aeEncodeGithubComGoParkMailRu20231TechnokaifInternalPkgPlaylistDeliveryHttp(w, v)
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *playlistUpdateInput) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonE5772aeDecodeGithubComGoParkMailRu20231TechnokaifInternalPkgPlaylistDeliveryHttp(l, v)
}
func easyjsonE5772aeDecodeGithubComGoParkMailRu20231TechnokaifInternalPkgPlaylistDeliveryHttp1(in *jlexer.Lexer, out *playlistCreateResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "id":
			out.ID = uint32(in.Uint32())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonE5772aeEncodeGithubComGoParkMailRu20231TechnokaifInternalPkgPlaylistDeliveryHttp1(out *jwriter.Writer, in playlistCreateResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.Uint32(uint32(in.ID))
	}
	out.RawByte('}')
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v playlistCreateResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonE5772aeEncodeGithubComGoParkMailRu20231TechnokaifInternalPkgPlaylistDeliveryHttp1(w, v)
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *playlistCreateResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonE5772aeDecodeGithubComGoParkMailRu20231TechnokaifInternalPkgPlaylistDeliveryHttp1(l, v)
}
func easyjsonE5772aeDecodeGithubComGoParkMailRu20231TechnokaifInternalPkgPlaylistDeliveryHttp2(in *jlexer.Lexer, out *playlistCreateInput) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "name":
			out.Name = string(in.String())
		case "users":
			if in.IsNull() {
				in.Skip()
				out.UsersID = nil
			} else {
				in.Delim('[')
				if out.UsersID == nil {
					if !in.IsDelim(']') {
						out.UsersID = make([]uint32, 0, 16)
					} else {
						out.UsersID = []uint32{}
					}
				} else {
					out.UsersID = (out.UsersID)[:0]
				}
				for !in.IsDelim(']') {
					var v4 uint32
					v4 = uint32(in.Uint32())
					out.UsersID = append(out.UsersID, v4)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "description":
			if in.IsNull() {
				in.Skip()
				out.Description = nil
			} else {
				if out.Description == nil {
					out.Description = new(string)
				}
				*out.Description = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonE5772aeEncodeGithubComGoParkMailRu20231TechnokaifInternalPkgPlaylistDeliveryHttp2(out *jwriter.Writer, in playlistCreateInput) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"name\":"
		out.RawString(prefix[1:])
		out.String(string(in.Name))
	}
	{
		const prefix string = ",\"users\":"
		out.RawString(prefix)
		if in.UsersID == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v5, v6 := range in.UsersID {
				if v5 > 0 {
					out.RawByte(',')
				}
				out.Uint32(uint32(v6))
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"description\":"
		out.RawString(prefix)
		if in.Description == nil {
			out.RawString("null")
		} else {
			out.String(string(*in.Description))
		}
	}
	out.RawByte('}')
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v playlistCreateInput) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonE5772aeEncodeGithubComGoParkMailRu20231TechnokaifInternalPkgPlaylistDeliveryHttp2(w, v)
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *playlistCreateInput) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonE5772aeDecodeGithubComGoParkMailRu20231TechnokaifInternalPkgPlaylistDeliveryHttp2(l, v)
}
func easyjsonE5772aeDecodeGithubComGoParkMailRu20231TechnokaifInternalPkgPlaylistDeliveryHttp3(in *jlexer.Lexer, out *defaultResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "status":
			out.Status = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonE5772aeEncodeGithubComGoParkMailRu20231TechnokaifInternalPkgPlaylistDeliveryHttp3(out *jwriter.Writer, in defaultResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"status\":"
		out.RawString(prefix[1:])
		out.String(string(in.Status))
	}
	out.RawByte('}')
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v defaultResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonE5772aeEncodeGithubComGoParkMailRu20231TechnokaifInternalPkgPlaylistDeliveryHttp3(w, v)
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *defaultResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonE5772aeDecodeGithubComGoParkMailRu20231TechnokaifInternalPkgPlaylistDeliveryHttp3(l, v)
}
func easyjsonE5772aeDecodeGithubComGoParkMailRu20231TechnokaifInternalPkgPlaylistDeliveryHttp4(in *jlexer.Lexer, out *PlaylistTransfers) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		in.Skip()
		*out = nil
	} else {
		in.Delim('[')
		if *out == nil {
			if !in.IsDelim(']') {
				*out = make(PlaylistTransfers, 0, 0)
			} else {
				*out = PlaylistTransfers{}
			}
		} else {
			*out = (*out)[:0]
		}
		for !in.IsDelim(']') {
			var v7 PlaylistTransfer
			(v7).UnmarshalEasyJSON(in)
			*out = append(*out, v7)
			in.WantComma()
		}
		in.Delim(']')
	}
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonE5772aeEncodeGithubComGoParkMailRu20231TechnokaifInternalPkgPlaylistDeliveryHttp4(out *jwriter.Writer, in PlaylistTransfers) {
	if in == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
		out.RawString("null")
	} else {
		out.RawByte('[')
		for v8, v9 := range in {
			if v8 > 0 {
				out.RawByte(',')
			}
			(v9).MarshalEasyJSON(out)
		}
		out.RawByte(']')
	}
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v PlaylistTransfers) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonE5772aeEncodeGithubComGoParkMailRu20231TechnokaifInternalPkgPlaylistDeliveryHttp4(w, v)
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *PlaylistTransfers) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonE5772aeDecodeGithubComGoParkMailRu20231TechnokaifInternalPkgPlaylistDeliveryHttp4(l, v)
}
func easyjsonE5772aeDecodeGithubComGoParkMailRu20231TechnokaifInternalPkgPlaylistDeliveryHttp5(in *jlexer.Lexer, out *PlaylistTransfer) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "id":
			out.ID = uint32(in.Uint32())
		case "name":
			out.Name = string(in.String())
		case "users":
			if in.IsNull() {
				in.Skip()
				out.Users = nil
			} else {
				in.Delim('[')
				if out.Users == nil {
					if !in.IsDelim(']') {
						out.Users = make([]http.UserTransfer, 0, 0)
					} else {
						out.Users = []http.UserTransfer{}
					}
				} else {
					out.Users = (out.Users)[:0]
				}
				for !in.IsDelim(']') {
					var v10 http.UserTransfer
					(v10).UnmarshalEasyJSON(in)
					out.Users = append(out.Users, v10)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "description":
			if in.IsNull() {
				in.Skip()
				out.Description = nil
			} else {
				if out.Description == nil {
					out.Description = new(string)
				}
				*out.Description = string(in.String())
			}
		case "isLiked":
			out.IsLiked = bool(in.Bool())
		case "cover":
			out.CoverSrc = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonE5772aeEncodeGithubComGoParkMailRu20231TechnokaifInternalPkgPlaylistDeliveryHttp5(out *jwriter.Writer, in PlaylistTransfer) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.Uint32(uint32(in.ID))
	}
	{
		const prefix string = ",\"name\":"
		out.RawString(prefix)
		out.String(string(in.Name))
	}
	{
		const prefix string = ",\"users\":"
		out.RawString(prefix)
		if in.Users == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v11, v12 := range in.Users {
				if v11 > 0 {
					out.RawByte(',')
				}
				(v12).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	if in.Description != nil {
		const prefix string = ",\"description\":"
		out.RawString(prefix)
		out.String(string(*in.Description))
	}
	{
		const prefix string = ",\"isLiked\":"
		out.RawString(prefix)
		out.Bool(bool(in.IsLiked))
	}
	if in.CoverSrc != "" {
		const prefix string = ",\"cover\":"
		out.RawString(prefix)
		out.String(string(in.CoverSrc))
	}
	out.RawByte('}')
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v PlaylistTransfer) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonE5772aeEncodeGithubComGoParkMailRu20231TechnokaifInternalPkgPlaylistDeliveryHttp5(w, v)
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *PlaylistTransfer) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonE5772aeDecodeGithubComGoParkMailRu20231TechnokaifInternalPkgPlaylistDeliveryHttp5(l, v)
}
