name: linters_and_tests

on: push

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.20'
        
      - name: Formatting
        run: gofmt -s -w -d . && git diff --exit-code

      - name: Verify dependencies
        run: go mod verify

      - name: Install golangci-lint
        run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.52.2
      - name: Run golangci-lint
        run: golangci-lint run --version --verbose --out-format=github-actions

      - name: go-vet
        run: go vet ./...

  test:
    runs-on: ubuntu-latest
    needs: check
    steps:
    - uses: actions/checkout@v3 
    - uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - run: make check_html_coverage
    - name: Upload coverage
      uses: actions/upload-artifact@v3
      with:
        path: ./cover.html
